import { RealEstateType } from './real-estate-type.enum';
import { Address } from '../../shared/models/address.entity';
import { RealEstateStatus } from './real-estate-status.enum';
import { RealEstateOrientation } from './real-estate-orientation.enum';
import { RealEstateAssignment } from './real-estate-assignment.enum';

export class RealEstate {
  id: number;
  type: RealEstateType;
  terraced: boolean;
  surface: number;
  totalSurface?: number;
  yearOfConstruction?: number;
  roomCount: number;
  floorNumber?: number;
  showerCount?: number;
  terraceCount?: number;
  hasGarden?: boolean;
  gardenSurface?: number;
  isSecured?: boolean;
  securityDetail?: string;
  facadeCount?: number;
  location?: string;
  orientation?: RealEstateOrientation;
  assignment?: RealEstateAssignment;
  price: number;
  priceCurrency: string;
  remark?: string;
  address: Address;
  owners: number[];
  buyers: number[];
  status: RealEstateStatus;
  statusRemark: string;
  saleDate?: Date;
  finalSellingPrice?: number;
  createdBy?: number;
  createdAt: Date;
  updatedBy?: number;
  updatedAt?: Date;
}
